<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "frp_keywords"
 *
 * Auto generated by Extension Builder 2014-04-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Add content tags',
	'description' => 'Allows content tags to be created and these to be associated with various content types (including pages).',
	'category' => 'plugin',
	'author' => 'Mark Howells-Mead',
	'author_email' => 'm.howells-mead@frappant.ch',
	'author_company' => '!frappant Webfactory',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>