require.config({
    paths:{
        'jquery':'https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min',
        'foundation':'https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.4/foundation.min',
        'foundation_core':'https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.4/foundation.core',
        'foundation_triggers':'https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.4/foundation.util.triggers',
        'foundation_mediaquery':'https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.4/foundation.util.mediaQuery'
    }
});

require([
    'jquery',
    'foundation',
    'foundation_core',
    'foundation_triggers',
    'foundation_mediaquery'
],function($,_){
    $(document).foundation();
});
